In [1]:
import numpy as np
import pandas as pd
import xlrd
import xlwt
import matplotlib.pyplot as plt

In [16]:
df = pd.read_excel('/Users/wenguo/Documents/Work/Liulab_质性评级/双评_1128.xlsx', sheet_name="双评原始数据")

In [18]:
df = df[['评分人','书名','等级','原label']]

In [20]:
df.head()

   评分人        书名   等级  原label
0  刘鋆钰   吹牛大王历险记  4.0     0.0
1   杨洋   吹牛大王历险记  5.0     0.0
2  刘鋆钰    大卫科波菲尔  5.0     0.0
3   杨洋    大卫科波菲尔  6.0     0.0
4  刘鋆钰  大象巴巴故事全集  3.0     0.0

In [23]:
table = pd.pivot_table(df, values='等级', columns = '评分人', index = '书名')

In [25]:
table

评分人                 任妍  刘鋆钰   杨洋  祁婉婷   葛瑞   韩旭
书名
会唱歌的小雨点微童话系列       2.0  NaN  NaN  NaN  NaN  1.0
吹牛大王历险记            NaN  4.0  5.0  NaN  NaN  NaN
哈利波特与阿兹卡班的囚徒       5.0  NaN  NaN  NaN  NaN  5.0
大卫科波菲尔             NaN  5.0  6.0  NaN  NaN  NaN
大象巴巴故事全集           NaN  3.0  1.0  NaN  NaN  NaN
女生贾梅全传             NaN  4.0  4.0  NaN  NaN  NaN
威斯利王国              NaN  3.0  2.0  NaN  NaN  NaN
我讨厌妈妈              NaN  NaN  NaN  0.0  1.0  NaN
手绢上的花田             NaN  NaN  NaN  2.0  3.0  NaN
福尔摩斯探案集            5.0  NaN  NaN  NaN  NaN  6.0
纳尼亚王国传奇1狮子、女巫和魔衣柜  NaN  4.0  3.0  NaN  NaN  NaN
绿野仙踪               2.0  NaN  NaN  NaN  NaN  3.0
罗伯特的三次报复行动         3.0  NaN  NaN  NaN  NaN  3.0
蚯蚓的日记              1.0  NaN  NaN  NaN  NaN  2.0
要是你给老鼠吃饼干          NaN  NaN  NaN  1.0  1.0  NaN
青鸟                 NaN  NaN  NaN  4.0  3.0  NaN

In [35]:
tp = [("任妍", "韩旭"), ("刘鋆钰", "杨洋"), ("祁婉婷", "葛瑞") ]
res = []

for pair in tp:
    p1,p2 = pair
    temp = table[[p1,p2]]
    temp = temp.dropna #(row = "NaN")
    corr = pd.corr()  #计算pearson相关系数；data.corr('spearman')计算spearman相关系数; data.corr('kendall')计算Kendall相关系数
    res.append(corr)

AttributeError: module 'pandas' has no attribute 'corr'

In [ ]:
res